# Generated by Django 3.0.7 on 2022-01-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200626_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
