# Generated by Django 3.0.7 on 2022-01-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_student_header_image'),
    ]

    operations = [
        
    ]
