# Generated by Django 3.0.7 on 2022-01-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220115_0037'),
    ]

    operations = [
        
    ]
