# Generated by Django 3.0.7 on 2022-01-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220115_0412'),
    ]

    operations = [
        
    ]
