# Generated by Django 3.0.7 on 2022-01-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220115_1920'),
    ]

    operations = [
        
    ]
