# Generated by Django 3.0.7 on 2022-02-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_student_vaccination_image'),
    ]

    operations = [
        
    ]
